# Generated by Django 4.2 on 2023-05-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empsys', '0003_employee_user_alter_employee_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='recipe_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
